version: '3.3'

services:
  nginx:
    image: nginx:1.23.3
    ports:
      - '8080:80'
    volumes:
      - .:/var/www/html/
      #- ./public:/public
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php-fpm
  
  php-fpm:
    build: ./docker/php-fpm
    volumes:
      - .:/var/www/html