
name: ci4-php8-docker

services:
- name: php-fpm
  image:
    registry_type: DOCR
    repository: php-fpm
    tag: latest
  internal_ports: 
    - 9000

- name: nginx
  image:
    registry_type: DOCR
    repository: nginx
    tag: latest
  http_port: 80
  routes:
  - path: /
